R/geotargets-option.R, R/tar-terra-vect.R, R/utils.R
This seems to get our codecov action working again, for #31, but I am not satisfied with this as a general solution. I do not understand at this time why it would matter if there was code in utils.R or not.
There seems to be some pretty odd stuff that can happen when target tests are being run inside testthat via covr.
=> Temporary coverage fix for #31

R/geotargets-option.R
In #30 I replaced the `unset` value returned by `Sys.getenv()` for GEOTARGETS_GDAL_RASTER_CREATION_OPTIONS
Calling `strsplit("", ";)[[1]]` returns `character(0)`, which will cause an error in `Sys.getenv()`. This PR gets us the intended default value of `""`
=> fix for empty GEOTARGETS_GDAL_RASTER_CREATION_OPTIONS

R/tar-terra-rast.R, R/tar-terra-vect.R
- Uses a simpler approach to updating the read/write function templates used in format creation methods, thanks to Will Landau for suggestion
- Fixes #38 by avoiding the problematic syntax, normal tests and tests in covr now work
=> `tar_format()` functions: Use `substitute()` into function body rather than `body<-`

DESCRIPTION, R/tar-terra-rast.R, R/tar-terra-vect.R, R/utils.R
Closes #10.  Moves `terra` to Suggests and moves check for `terra` to top of `tar_*()` functions.
Also moves validation of `filetype` to `tar_*()` functions. I think this might make error traces more readable to users, but haven't really tested thoroughly
=> Moves `terra` to Suggests

R/geotargets-option.R, R/tar-terra-rast.R, R/tar-terra-sprc.R, R/tar-terra-vect.R, R/utils.R, tests/testthat/_snaps/tar-terra-sprc.md, tests/testthat/test-tar-terra-sprc.R, tests/testthat/test-tar-terra.R
Here are some things I noticed while bringing the tar-stars (#33) branch up to date. Doing a separate PR as they are not related to the {stars} changes
In this PR:
- `geotargets_option_get()`: Handle case when `getOption()` returns vector length >1
- `get_gdal_available_driver_list()`: Fix for `terra::gdal(drivers=TRUE)` table format. This has changed in the development version of terra (currently 1.7-75 vs. CRAN 1.7-71). For now handle older package versions differently by checking with `packageVersion()` before subsetting driver list. {terra} now reports drivers similarly to how {sf} does RE: https://github.com/rspatial/terra/issues/1465
- `tar_terra_sprc()`: Fix specification of multiple raster creation options in test and add snapshot
=> Fixes after options, terra, and `tar_terra_sprc()` updates

R/geotargets-option.R, R/tar-terra-rast.R, R/tar-terra-sprc.R, R/tar-terra-vect.R, R/utils.R, tests/testthat/test-tar-terra-sprc.R
Removes some repeated or unnecessary code I noticed in `tar_terra_sprc()`.  Implements suggestion in #61.
=> `tar_terra_sprc()` simplification

NEWS.md, R/tar-terra-rast.R, R/tar-terra-sprc.R, R/tar-terra-vect.R, tests/testthat/test-geotargets-option.R, tests/testthat/test-tar-terra.R
Fix for #66.  Uses `utils::modifyList()` to append the user supplied `resources` with those necessary for `tar_terra_*()` to work. Also includes changes to tests that were needed to get `check()` to pass
=> Pass user specified `resources`

.github/workflows/R-CMD-check.yaml
=> Add a step to github action to print GDAL version

.Rbuildignore, CITATION.cff, R/release_bullets.R
Adds a CITATION.cff file that will be recognized by GitHub and Zenodo.  Also adds a reminder to update it when using `usethis::use_release_issue()`
=> Add CITATION.cff

NEWS.md, R/tar_terra_tiles.R, tests/testthat/test-tar-terra-tiles.R
Closes #87 by using only the first row of output from `terra::fileBlocksize()`, which outputs a number of rows and columns *for each layer*.
=> Fix `tile_blocksize()` to work with multi-layer rasters

NEWS.md, R/tar-terra-vect.R, R/utils.R, tests/testthat/_snaps/check-gdal-shz.md, tests/testthat/test-check-gdal-shz.R
Closes #71 by adding a check for GDAL 3.1 or greater.  Not sure if there is a way to write a test for this
=> Adds GDAL min version requirement for writing .shz

DESCRIPTION, R/tar-stars.R, R/tar-terra-rast.R, R/tar-terra-sprc.R, R/tar-terra-vect.R, R/tar_terra_tiles.R, man/tar_stars.Rd, man/tar_terra_rast.Rd, man/tar_terra_sds.Rd, man/tar_terra_sprc.Rd, man/tar_terra_tiles.Rd, man/tar_terra_vect.Rd, tests/testthat/test-tar-terra.R
The newest release of `targets` (1.8.0) introduces a new way to pass arguments to custom read and write functions inside of `tar_format()` using a `substitute` argument (#101).  This makes the code a little bit cleaner (no more passing of environment variables with the `resources` argument) and happens to fix an issue where changing the `filetype` argument didn't invalidate the target (#103).
Since we use @inheritParams quite a bit, the documentation for `geotargets` is also updated, sometimes in ways that seem less than ideal (e.g. mentioning specifically `tar_target()` and `tar_target_raw()`.  I suggest that any edits to documentation be dealt with in a separate PR.
=> Simpler `tar_format()` with `targets` 1.8.0

R/geotargets-option.R, R/tar-stars.R, R/tar-terra-rast.R, R/tar-terra-sprc.R, R/tar-terra-vect.R, R/tar_terra_tiles.R, man/geotargets-options.Rd, man/set_window.Rd, man/tar_stars.Rd, man/tar_terra_rast.Rd, man/tar_terra_sds.Rd, man/tar_terra_sprc.Rd, man/tar_terra_tiles.Rd, man/tar_terra_vect.Rd, man/tile_helpers.Rd
This closes #107 by adding documentation for the name, command, and pattern parameters to all `tar_*()` functions rather than relying on importing the documentation for these from `targets`
=> custom documentation for name, command, and pattern params

NEWS.md, R/tar-terra-sprc.R, tests/testthat/test-tar-terra-sprc.R
Addresses #92 by wrapping the write function in `withCallingHandlers()` to capture the uninformative warning `[rast] skipped sub-datasets ...`.  The warning originates from `terra::writeRaster()` when it is used to write a subdataset because the return value of `writeRaster()` is `rast(<file>)` and that file can't be correctly read by `rast()` if it has subdatasets with different projections.
This was difficult to add a test for since warnings from write functions apparently don't bubble up to the output of `tar_meta()`.  I added a test for a version of the write function instead.
=> Suppress `tar_terra_sprc()` warning

DESCRIPTION, R/tar-stars.R
Deals with two `check()` notes:
- adds `fs` to Suggests (it is used in vignette)
- moves `geotargets:::check_pkg_installed()` outside of a write function so it can just be `check_pkg_installed()`
=> handle check() notes

R/tar_terra_tiles.R, man/tar_stars.Rd, man/tar_terra_rast.Rd, man/tar_terra_sds.Rd, man/tar_terra_sprc.Rd, man/tar_terra_tiles.Rd, man/tar_terra_vect.Rd, man/tile_helpers.Rd
Add documentation to `tar_terra_tiles()` and `tile_blocksize()` explaining why and how to force upstream targets to not be in memory.
Also updates other documentation because of running `document()` with `targets` 1.9.0 installed
=> Document workaround for issues with `tile_blocksize()` (#99)

R/tar-terra-rast.R, tests/testthat/test-tar-terra-rast.R
In my quest to preserve metadata in raster targets I accidentally forgot to preserve the **data**.  We can't use `withr::local_tempdir()` in the read function because it'll get cleaned up and the resulting `SpatRaster` will have a broken file pointer.  I don't love this solution, but the only other workaround I can think of is to force the `SpatRaster` to point to memory (e.g. by adding 0 or multiplying by 1 after reading), and I like that solution less I think.
Fixes #127.
=> Fix missing data when `preserve_metadata = "zip"`

tests/testthat/test-tar-terra-tiles.R
=> add tests to ensure tile splits recombine appropriately

tests/testthat/test-tar-stars.R
This skips the `tar_stars()` tests that require use of `ncmeta` to write netCDF files when `ncmeta` is not installed.
=> tar_stars: skip test with ncdf=TRUE when ncmeta is not installed

NEWS.md, R/geotargets-option.R, R/tar-terra-vect.R, man/geotargets-options.Rd, man/tar_terra_vect.Rd
Closes #166 by switching default driver to GPKG for `tar_terra_vect()`
=> Change default driver for SpatVectors to GPKG

README.Rmd, README.md
No rush---typo is obvious!---but could momentarily mislead the casual copy-paster.
=> README typos `tar_tera_tiles`>`tar_terra_tiles`

R/geotargets-option.R, R/tar-stars.R, R/tar-terra-vrt.R, man/geotargets-options.Rd, man/tar_terra_vrt.Rd
- add missing return value for `tar_terra_vrt()`
- fix GDAL URLs that redirect in the source files. Some look like they are updated in .Rd, also fixed one in `tar_stars()`
=> Doc updates

man/tar_stars.Rd, man/tar_terra_rast.Rd, man/tar_terra_sds.Rd, man/tar_terra_sprc.Rd, man/tar_terra_tiles.Rd, man/tar_terra_vect.Rd, man/tar_terra_vrt.Rd, tests/testthat/_snaps/tar-terra-rast.md, tests/testthat/_snaps/tar-terra-sprc.md
This addresses failing pkgcheck by updating some snapshots that changed because of apparent changes in `terra` print methods.  It also updates documentation inherited from `targets`
=> Snapshot test update
